kind: pipeline
name: Signature Drone

steps:
 - name: compile
   image: fajar4561/saciku:latest
   environment:
     TG_CHAT_ID:
       from_secret: TG_CHAT_ID
     TG_TOKEN:
       from_secret: TG_TOKEN
     AWAL:
       from_secret: AWAL
     AKHIR:
       from_secret: AKHIR
   commands:
      - git config --global user.name "$AWAL"
      - git config --global user.email "kendras056@gmail.com"
      - git clone --depth=1 https://$AWAL:$AKHIR@github.com/Kendras056/kernel_X00T -b master kernel && cd kernel
      - curl https://raw.githubusercontent.com/Kendras056/My-kernel-builder/main/build.sh > run.sh
      - bash run.sh
